apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ord.name }}
  namespace: {{ .Values.ord.org }}
spec:
  selector:
    app: hyperledger
    role: orderer
    orderer-id: {{ .Values.ord.name }}
    org: {{ .Values.ord.org }}
  type: NodePort
  ports:
  - name: listen-endpoint
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
